### ISSUE TITLE
Pass icon missing and hanging pass instances exist

### ISSUE THREAD

**Issue by belak** [jvenant/passff#146]
I recently Re-installed firefox on my Mac and was trying to get this working... however pass is in /usr/local/bin/pass, so the first time I started it up, there was an error. I changed to the proper path and restarted Firefox (for good measure) but the pass icon had disappeared and there was a hanging pass process eating up CPU. It seems odd that it was being run through bash, as I have "Direct Call" selected.

```
~ % ps aux | grep pass
belak            1153 100.0  0.0  2454892   1276   ??  R    11:45AM   0:05.25 bash /usr/local/bin/pass
belak            1173   0.0  0.0  2434840    760 s010  S+   11:45AM   0:00.00 grep --color=auto pass
```

Note that the hanging pass processes also cause firefox to fail to close properly. Firefox hangs when closing until the bug reporter kicks in, but will instantly close if I manually kill the process.

I have seen other missing icon issues, but they didn't seem like the same thing I've been running into. If I can do anything to help debug, please let me know.

**Comment by belak** [comment]
Note that the hanging pass processes also cause firefox to fail to close properly. Firefox hangs when closing until the bug reporter kicks in.

**Comment by phryneas** [comment]
Just to get that misconception out of the way:
pass is a bash script and thus can never been run without invoking bash, so this is totally normal behaviour for "direct call". 
"through bash" wraps that bash into what is called a "login shell", that loads files like .bashrc as if it were called interactively in the terminal - this way environment variables can be set that wouldn't be set otherwise.

Back on the problem with the hanging process:

Could you do a `ps auxf | grep pass -A10` or, if that doesn't give a process tree on mac `pstree | grep pass -A10`? Most likely not pass itself is hanging, but a process that is spawned by pass is waiting for some kind of interaction.

**Comment by belak** [comment]
Ah, it's probably the default gpg client which asks for the passphrase on stdin... I'll double check when I get home.

**Comment by belak** [comment]
Switching to a gpg implementation which opens a window seems to fix this. Thanks!
