### ISSUE TITLE
Pages where autofill doesn't work

### ISSUE THREAD

**Issue by denydias** [jvenant/passff#54]
I'm wondering if here is the best place for this, but here I go anyway. If I'm wrong, I apologize and expect some advice of the proper place.

I'm using passff for about 24h now and I've been careful enough to migrate most of my former password management utility by hand to avoid any conflicts in the conversion process. I followed exactly the structure proposed in the [README.md](/jvenant/passff/blob/master/README.md#usage), which is:

```
<the_password>
login: <the_login>
url: <the_url>
```

For the sake of clarity, I've changed the `login` field to `user`.

It's working on almost every account I'm managing with `pass`, except these two bellow. In all the mentioned cases, when I chose `Display` in passff popup window both login and password data looks ok (they are the ones set for that page URL).

### Instagram

**url:** https://instagram.com/accounts/login/
**behavior:** Here the login form is included through an iframe (o.O). It appears that passff is able to fill forms in the pages that has been loaded straight by the browser, and not for the ones loaded indirectly via iframes.

### TIM (Telecom Italia Mobile, Brazil)

**url:** https://meutim.tim.com.br/login
**behavior:** In this one, the password field (`name="senha"`) gets filled fine, but not the login one (`name="loginField"`). I have set the field name into `Login input names` field at passff preferences, but it's still a no go. The `loginField` length is 13 characters in the form: `(##)#########`. The parenthesis are not optional and the `#` must be numbers from 0 to 9.

These are the ones I have for now. As I found more exceptions, I'll come back here to notify.

**Comment by denydias** [comment]
Just found another one.

### Sem Parar (Brazil)

**url:** https://appsol.viafacil.com.br/sol/jsp/sol/frames/frameInicial.jsp
**behavior:** In this page the field marked with `CPF/CNPJ` label (`name="cgcpf"`) is the user name and  the one marked with `SENHA` (`name="senha"`) is the password. Nome of them are filled with the values from `pass`. The `cgcpf` field is 14 characters, numbers only.

**Comment by jvenant** [comment]
Hi @denydias,

Thank you for your very precise feedback.

I publish a new release that should fix some of your issues here : [v1-pre-release-19](https://github.com/jvenant/passff/releases/tag/v1-pre-release-19)
Actually, there was 2 problems :
* For TIM, the input filter was too restrictive : input with a "tel" type were not filled.
* For the 2 others (Instagram and Sem Parar), as you said, the inputs were in an iframe.

For the first problem, the solution was simple : I add "tel" in the inputs filter.
For the second problem, it's a little bit more tricky : it's about processing embed iframes.
Considering how weird some web sites can be, I limit the input search to only the first level of iframes. This should prevent some deep recursive issues.
It works for instagram, but not for sem parar because the inputs are in the second iframe level (inputs are inside an iframe inside an iframe inside the page).

I haven't implemented a solution yet for this : 
* I could not limit the search to the first level of iframe : maybe it is not an issue to process all the iframes of the page recursively.
* I could search deeper to the second iframe level.
* Or add a (hidden?) preference to set how deep passff must search.

Let me know if somebody have any suggestion about this.

**Comment by tuxor1337** [comment]
I would suggest to choose the recursive implementation. Just add a global variable that keeps track of the depth of recursion and abort the process when recursion level exceeds something like 10 or so.

**Comment by jvenant** [comment]
Ok, recursive search implemented here : [v1-pre-release-20](https://github.com/jvenant/passff/releases/tag/v1-pre-release-20)

And thank you for your encouragement @tuxor1337  :wink:

**Comment by jvenant** [comment]
So basically, "sem parar" should also works now

**Comment by denydias** [comment]
Hi @jvenant,

Thank you for the quick reply and fix!

Sem Parar and TIM indeed worked great! Instagram doesn't. It gets filled with login content, but fails to login upon submit. When displaying the login content, the data looks fine. How do I check the values filled by passff before submit in the page itself so I can trace the issue down?

As @tuxor1337 said, the recursion feature is quite elegant indeed. I also agree with him and with you that a hidden preference would be nice, as there could be some nasty webpages out there that do not deserve an infinite loop just to fill the login data.

**Comment by denydias** [comment]
Oh! A last question: should we report non working pages here in this issue or do you prefer to treat them in separate issues?

**Comment by jvenant** [comment]
For security reason, I never log logins and passwords. Even in debug mode. But you can display the login password using the "Display" command in the contextual menu. Maybe check that there is no trailing spaces in your password... Or maybe it's instagram who do some weird stuff with the login/password inputs... You could try adding/removing characters in the inputs and submit after to see if there is some king of focus/keypressed behavior that may explain this...

I prefer to treat non working pages in separate issues as they could be caused by different reason

Thank you very much for your feedbacks

**Comment by denydias** [comment]
Hi @jvenant, thank you for the reply.

There's no trailing characters of any form in the password. The user field in the `pass` file is `user:<space>word`, but `pass` is able to deal with that space and do not prints it to the output.

I was not talking about log what passff send to pages. I agree with you that this is a HUGE security hole and should never be implemented.

What I was looking for instead is a way to accomplish this:

1. Open the page where the account should be filled;
2. Let passff fill the form with user data, but do not submit;
3. At this point the page fields is going to contain data;
4. Using available development tools (embed to web browser or via addons), inspect the input elements to see what are the data inside them. This could be Firefox's own Inspect Element or Console Log features.

Is there a way to see that data?

**Comment by jvenant** [comment]
you could probably do this using the web console (Ctrl + Shift + K or Tools / Web developer / Web console).
* First, get the Id of the input using the pick element button. Click the button (the one at the upper left with an arrow in front on a square) and pick the input you want to inspect. Get the value of the id attribute.
* Next got on the "console" tab. At the bottom you have a command line where you can execute any javascript you want.
* try to execute something like : alert(document.getElementById('input_id').value) replacing "input_id" by the id of your input.

You should get the exact value of the field.

**Comment by tuxor1337** [comment]
By the way: You solved the problem with iframes now. But what about "real" framesets?

**Comment by jvenant** [comment]
Nothing right now about framesets. But does anybody use that anymore ?
I mean : it even no more part of the html5 standard...

**Comment by tuxor1337** [comment]
I get your point. I hate framesets and they are deprecated. Maybe we can ignore them.

The reason I'm asking: I was running into problems with the UI of my router (an AVM Fritz!Box). But since it's only a single frame in that frameset (pretty pointless actually), I can directly access the URL of that particular frame (http://fritz.box/login.lua) instead of the URL of the frameset (http://fritz.box/). So let's ignore frames until somebody comes up with a big web page that really needs it (probably never going to happen...).

**Comment by denydias** [comment]
Hi, @tuxor1337!

The method you suggested works perfectly. But there are some caveats. As the login form itself is inside an iframe, one have to right click and choose 'this frame' only. This will give this page:

https://instagram.com/accounts/login/ajax/?targetOrigin=https%3A%2F%2Finstagram.com

All the data filled by passff are exactly the same as the one set in `pass`. No extra spaces, no strange characters, nothing wrong. The above pages doesn't let you login as the ajax elements need by the auth process aren't there. It's useful only to verify the data sent by passff to the form.

Oddly enough, it still doesn't work. It keeps insisting that user credentials are wrong. Maybe the iframe loop is inserting some strange characters in the original data.

I think we've faced a dead end in this issue due to facebook idiosyncrasies.

**Comment by jvenant** [comment]
You could try adding / removing an extra characters in the login and password inputs. Just to see if it is linked to some kind of linked javascript event...

**Comment by denydias** [comment]
Oh! Sorry, @jvenant! I totally missed this one! Busy times here. I didn't have tested your debug suggestion yet, but it's in my pipeline. If I figure something out, I'll open a new issue.

Thank you and sorry.
