### ISSUE TITLE
Sensible defaults for OS X

### ISSUE THREAD

**Issue by sometoby** [jvenant/passff#72]
It would be more convenient if the pass script configuration defaulted to the known workaround on OS X.

**Comment by phryneas** [comment]
This is a bit difficult, since it is platform-specific and user-configuration-specific.

On Windows, it can default to the MSYS2 bash, the minGW bash or the cygwin bash. On OSX and Linux it defaults to /bin/bash.

But only under one condition: the user is using bash. I, for my part, am using zsh, and only zsh is configured correctly (PATH, LANG etc.) for pass to run at all. Bash would not work for me.

But this would make a fine update of the README.md - if you feel like it, pull requests are always welcome?

**Comment by sometoby** [comment]
It certainly is difficult to get perfect, but all I am to do is adjust the settings when running on OS X the first time to match a configuration that is known to work for most users. This will definitely increase the chance of passff "just working" after being installed.
